### ISSUE TITLE
Jetty with Weld And JSF

### ISSUE THREAD

**Issue by salviof** [jetty-project/weld-example-base#1]
Why is so hard run Jetty, with Weld 2.2.16.SP1, and JSF 2.2.1 ? thats works only in tomcat..
Is that possible ?    (without INFO: WELD-ENV-001001-> No supported servlet container detected, CDI injection will NOT be available in Servlets, Filters or Listeners)

Thanks.

**Comment by janbartel** [comment]
Have you read the jetty weld doco here: http://www.eclipse.org/jetty/documentation/9.3.x/framework-weld.html

Also, what version of jetty are you using?  What is the webapp you are using, how have you configured it?

**Comment by salviof** [comment]
Hello, Janbardel, thanks, Yes, I Read and do that, weld works fine with beans, but, inside servlet classes dont, the  version are  9.3.11.v20160721 
When weld initizalize, I receve this message:

NFO: WELD-ENV-001001: No supported servlet container detected, CDI injection will NOT be available in Servlets, Filters or Listeners

:(
If you want and can to help me , I can create a small application to download with a samle .. thanks
Thats.;

**Comment by janbartel** [comment]
@salviof yes, we would need a small application that demonstrates the problem to get any further. Thanks.

**Comment by salviof** [comment]
Hello Jan, Today I got resolve!  now I can use Inject from weld CDI with jetty!   
Thats was about Decoretor class load, (org.eclipse.jetty.servlet.ServletContextHandler.Decorator)

In article: [](http://www.agorava.org/news/2012/07/10/Starting-a-CDI-webapp-from-Maven-with-Weld-servlet-and-jetty-plugin/)  
The author explains that Weld needs to decorate some Jetty internal classes in order to use the @Inject annotation in servlets and that we have to tell the Jetty classloader where to find this class in order to have the Weld servlet to decorate it.

My jettyweb.xml now are like that:

<Configure id="webAppCtx" class="org.eclipse.jetty.webapp.WebAppContext">

    <New id="BeanManager" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg>
            <Ref id="webAppCtx"/>
        </Arg>
        <Arg>BeanManager</Arg>
        <Arg>
            <New class="javax.naming.Reference">
                <Arg>javax.enterprise.inject.spi.BeanManager</Arg>
                <Arg>org.jboss.weld.resources.ManagerObjectFactory</Arg>
                <Arg/>
            </New>
        </Arg>
    </New>
    <Set name="serverClasses">
        <Array type="java.lang.String">
            <Item>org.eclipse.jetty.servlet.ServletContextHandler.Decorator</Item>
        </Array>
    </Set>



</Configure>


Thanks!
